version: '3.9'

services:
    prisma-react-frontend:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        container_name: prisma-react-frontend
        ports:
            - 3001:3001
        restart: always
        networks:
            - shared_network

networks:
    shared_network:
        driver: bridge
        name: shared_network
