import React from 'react'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import 'tailwindcss/tailwind.css'
// import { AuthProvider } from './contexts/AuthContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MedLife',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <AuthProvider> */}
        <body className={inter.className}>{children}</body>
      {/* </AuthProvider> */}
    </html>
  )
}
